# Generated by Django 4.1.3 on 2022-11-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='goal',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
